CREATE TABLE worker_revision(id INTEGER PRIMARY KEY CHECK(id=1),revision INTEGER NOT NULL);
INSERT INTO worker_revision VALUES(1,0);
CREATE TABLE worker_guard(id INTEGER PRIMARY KEY CHECK(id=1),ok INTEGER NOT NULL CHECK(ok=1));
CREATE TABLE worker_import(id INTEGER PRIMARY KEY CHECK(id=1),source_digest TEXT NOT NULL,verified INTEGER NOT NULL DEFAULT 0 CHECK(verified IN(0,1)));
CREATE TRIGGER revision_schema_version_insert AFTER INSERT ON schema_version BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_schema_version_update AFTER UPDATE ON schema_version BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_schema_version_delete AFTER DELETE ON schema_version BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_employees_insert AFTER INSERT ON employees BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_employees_update AFTER UPDATE ON employees BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_employees_delete AFTER DELETE ON employees BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_tasks_insert AFTER INSERT ON tasks BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_tasks_update AFTER UPDATE ON tasks BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_tasks_delete AFTER DELETE ON tasks BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_users_insert AFTER INSERT ON users BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_users_update AFTER UPDATE ON users BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_users_delete AFTER DELETE ON users BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_sessions_insert AFTER INSERT ON sessions BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_sessions_update AFTER UPDATE ON sessions BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_sessions_delete AFTER DELETE ON sessions BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_attendance_insert AFTER INSERT ON attendance BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_attendance_update AFTER UPDATE ON attendance BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_attendance_delete AFTER DELETE ON attendance BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_production_insert AFTER INSERT ON production BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_production_update AFTER UPDATE ON production BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_production_delete AFTER DELETE ON production BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_overtime_insert AFTER INSERT ON overtime BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_overtime_update AFTER UPDATE ON overtime BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_overtime_delete AFTER DELETE ON overtime BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_audit_insert AFTER INSERT ON audit BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_audit_update AFTER UPDATE ON audit BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_audit_delete AFTER DELETE ON audit BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_qr_challenges_insert AFTER INSERT ON qr_challenges BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_qr_challenges_update AFTER UPDATE ON qr_challenges BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_qr_challenges_delete AFTER DELETE ON qr_challenges BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_qr_uses_insert AFTER INSERT ON qr_uses BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_qr_uses_update AFTER UPDATE ON qr_uses BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_qr_uses_delete AFTER DELETE ON qr_uses BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_deletion_confirmations_insert AFTER INSERT ON deletion_confirmations BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_deletion_confirmations_update AFTER UPDATE ON deletion_confirmations BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_deletion_confirmations_delete AFTER DELETE ON deletion_confirmations BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_login_limits_insert AFTER INSERT ON login_limits BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_login_limits_update AFTER UPDATE ON login_limits BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_login_limits_delete AFTER DELETE ON login_limits BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_initial_setup_insert AFTER INSERT ON initial_setup BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_initial_setup_update AFTER UPDATE ON initial_setup BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_initial_setup_delete AFTER DELETE ON initial_setup BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_work_requests_insert AFTER INSERT ON work_requests BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_work_requests_update AFTER UPDATE ON work_requests BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_work_requests_delete AFTER DELETE ON work_requests BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_work_request_history_insert AFTER INSERT ON work_request_history BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_work_request_history_update AFTER UPDATE ON work_request_history BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE TRIGGER revision_work_request_history_delete AFTER DELETE ON work_request_history BEGIN UPDATE worker_revision SET revision=revision+1 WHERE id=1; END;
CREATE INDEX attendance_date_employee ON attendance(date,employee_id);
CREATE INDEX production_date_employee ON production(date,employee_id);
CREATE INDEX production_employee_date ON production(employee_id,date);
CREATE INDEX sessions_expiry ON sessions(expires);
CREATE INDEX work_requests_dates ON work_requests(start_date,end_date);
CREATE INDEX users_employee ON users(employee_id);
